add subfield a if missing

diff --git a/marcfix b/marcfix
--- a/marcfix
+++ b/marcfix
@@ -1,3 +1,22 @@
+#!/usr/bin/bash
+
+deepclean="no"
+
+while getopts "d" opt; do
+  case $opt in
+    d)
+      deepclean="yes"
+      ;;
+    \?)
+      echo "Error: Invalid option -$OPTARG" >&2
+      echo "Usage: $0 [-d]" >&2
+      exit 1
+      ;;
+  esac
+done
+
+shift $((OPTIND - 1))
+
 filelist=("$@")
 
 rm -f bad_length*
@@ -17,8 +36,11 @@ read -r -d '' awkscript << "ENDOFAWK"
 #!/usr/bin/awk -f 
 
 BEGIN { goodrecs=badrecs=deletedrecs=bad001=badleader=baddirectory=bibcount=holdingscount=authoritycount=0
+	subfield_a = SFS"a" 
 	subfield_0 = SFS"0" 
 	subfield_9 = SFS"9"
+	subfield_any = SFS"."
+	not_subfield = "[^"FS"]"
 	BAD_INDICATOR_REGEX=FS".?"SFS
 }
 function check_fields() {
@@ -38,13 +60,33 @@ function check_fields() {
 
 	if (directory_check == 0) {
 		for (i=1; i<=directory_length; i=i+12) {
+			if (DEEPCLEAN == "yes") {
+				field_length = substr(directory, i + 3, 4) + 0
+				starting_pos = substr(directory, i + 7, 5)
+				field_content = substr(record_content, starting_pos + 1, field_length - 1)
+
+				field_start_address = baseaddress + starting_pos 
+				field_end_address = field_start_address + length(field_content) + 1
+			} 
+
 			tag = substr(directory, i, 3)
 			if (tag == "004") {
 				if (rectype !~ "holdings" ) { $0 = substr($0, 1, 6)"y"substr($0, 8); }
 				rectype="holdings"
 			}
 			if (tag == "008") {found008 = 1}
-			if (tag == "245") {override245=found245=1;rectype="bib"}
+			if (tag == "245") {
+				override245=found245=1
+				rectype="bib"
+
+				if (DEEPCLEAN == "yes") {
+					### adds subfield a if missing
+					if (field_content !~ /subfield_a/) {	
+						sub(subfield_any, subfield_a, field_content)
+						$0 = substr($0, 1, field_start_address)""field_content""substr($0, field_end_address)
+					}
+				}
+			}
 			if (tag ~ /[A-Z]/) {
 				if (!tag_seen[tag]) {
 					tag_count[tag]++
@@ -67,6 +109,8 @@ function check_leader() {
 	directory_check=(directory_length % 12)
 	record_length = length($0) + 0
 	reported_length = substr($0, 1, 5) - 1
+
+	if (DEEPCLEAN == "yes"){ record_content=substr($0, baseaddress + 1) }
 
 	if (record_length > 99999) {oversized = 1;totaloversized++;print $0 > "tmp_oversized.mrc"}
 	
@@ -208,7 +252,7 @@ process_file() {
 	bad_subfield_regex1=$'\x1f'[0az]$'\x1e'
 	bad_subfield_regex2=$'\x1f'[^0-9a-z]
 
-	awk -v RS=$'\x1d' -v ORS=$'\x1d' -v FS=$'\x1e' -v SFS=$'\x1f' -v FILEROOT="${fileroot}" -v BAD_SUBFIELD_REGEX1=${bad_subfield_regex1} -v BAD_SUBFIELD_REGEX2=${bad_subfield_regex2} -b -f tmp_checkmarc "${marcfile}"
+	awk -v RS=$'\x1d' -v ORS=$'\x1d' -v FS=$'\x1e' -v SFS=$'\x1f' -v FILEROOT="${fileroot}" -v BAD_SUBFIELD_REGEX1=${bad_subfield_regex1} -v BAD_SUBFIELD_REGEX2=${bad_subfield_regex2} -v DEEPCLEAN=${deepclean} -b -f tmp_checkmarc "${marcfile}"
 	sleep 1
 	
 	ls bad_*"${fileroot}" 2> /dev/null
