make negative match explicit

diff --git a/marcextractbyid b/marcextractbyid
--- a/marcextractbyid
+++ b/marcextractbyid
@@ -1,3 +1,22 @@
+#!/usr/bin/bash
+
+negativematch="no"
+
+while getopts "n" opt; do
+  case $opt in
+    n)
+      negativematch="yes"
+      ;;
+    \?)
+      echo "Error: Invalid option -$OPTARG" >&2
+      echo "Usage: $0 [-n]" >&2
+      exit 1
+      ;;
+  esac
+done
+
+shift $((OPTIND - 1))
+
 if [[ -z $1 ]];then
 	echo
    echo "Usage: marcextractbyid [filename] [marcid_field]"
@@ -10,6 +29,9 @@ if [[ -z $1 ]];then
    echo "Usage: marcextractbyid [filename] [id_value] [marcid_field]"
    echo "Usage: marcextractbyid [filename] [id_value]"
    echo
+   echo "Options:"
+   echo "-n Negative match. Show records that don't any ids in file"
+	 echo
    exit
 fi	
    infile="${1}"
@@ -38,10 +60,10 @@ fi
 if [[ -z $idtag ]];then idtag="001";fi
 
 fileroot=$(echo "${infile}" | sed 's/\.....\?$//')
-matched="${fileroot}_matched.mrc"
-notmatched="${fileroot}_not-matched.mrc"
 
-rm -f "${matched}" "${notmatched}"
+[[ ${negativematch} == "no" ]] && outfile="${fileroot}_matched.mrc" || outfile="${fileroot}_not-matched.mrc"
+
+rm -f "${outfile}"
 
 read -r -d '' awkscript << "ENDOFAWK"
 #!/usr/bin/awk -f 
@@ -105,25 +127,16 @@ if (directory_check == 0) {
 
 gsub(" *$", "", id_content)
 
-if (seen[id_content] == 1 ) { found = 1 }
-
+if (seen[id_content] == 1 ) { 
+	foundrecs++
+	if ( NEGATIVEMATCH == "no" ) { print $0 > OUTFILE }
+	if (SINGLEID == 1) { exit }
+} else {
+	notfoundrecs++
+	if ( NEGATIVEMATCH == "yes" ) { print $0 > OUTFILE }
+}
 id_content = ""
 
-}
-
-if (SINGLEID == 0) {
-	if (found == 1 ) {
-	        foundrecs++
-	        print $0 > MATCHED
-	} else {
-	        notfoundrecs++
-	        print $0 > NOTMATCHED
-	}
-} else {
-	if (found == 1 ) {
-		print $0 > MATCHED
-		exit
-	}
 }
 
 recordcounter++
@@ -138,13 +151,13 @@ echo -e "${awkscript}" > tmp_checkmarc
 chmod 700 tmp_checkmarc
 
 
-awk -v ORS=$'\x1d' -v FS=$'\x1e' -v RS=$'\x1d' -v SFS=$'\x1f' -v IDTAG=${idtag} -v MATCHED="${matched}" -v NOTMATCHED="${notmatched}" -v SINGLEID=${singleid} -b -f tmp_checkmarc "tmp_ids" "${infile}"
+awk -v ORS=$'\x1d' -v FS=$'\x1e' -v RS=$'\x1d' -v SFS=$'\x1f' -v IDTAG=${idtag} -v OUTFILE="${outfile}" -v NEGATIVEMATCH="${negativematch}" -v SINGLEID=${singleid} -b -f tmp_checkmarc "tmp_ids" "${infile}"
 echo
 echo
 
 if [[ ${singleid} == 0 ]];then
-	echo "Records matching ID file were output to ${matched}                     " 
-	echo "Records not matching ID file were output to ${notmatched}                     " 
+	 [[ ${negativematch} == "yes" ]] && echo "Records not matching ID file were output to ${outfile}                     "
+	 [[ ${negativematch} == "no" ]] && echo "Records matching ID file were output to ${outfile}                     "
 	echo
 fi
 if [[ ${singleid} == 1 && -f ${matched} ]];then
